
# Monitor 1 gets odd-numbered workspaces
workspace=1, monitor:DP-1, persistent:true
workspace=3, monitor:DP-1, persistent:true
workspace=5, monitor:DP-1, persistent:true
workspace=7, monitor:DP-1, persistent:true
workspace=9, monitor:DP-1, persistent:true

# Monitor 2 gets even-numbered workspaces
workspace=2, monitor:DP-2, persistent:true
workspace=4, monitor:DP-2, persistent:true
workspace=6, monitor:DP-2, persistent:true
workspace=8, monitor:DP-2, persistent:true


# window rules
windowrule = workspace 1 silent, match:class ^(Alacritty)$
windowrule = workspace 2 silent, match:class ^(chromium).*$
windowrule = workspace 3, match:class ^(chrome-chatgpt).*$
windowrule = workspace 4, match:class ^(org.gnome.Nautilus).*$
windowrule = workspace 7 silent, match:class ^.*thunderbird.*$
windowrule = workspace 7 silent, match:class ^(chrome-mail.google.com).*$
windowrule = workspace 8 silent, match:class ^(chrome-web.whatsapp).*$
windowrule = workspace 9 silent, match:class ^.*keepassxc.*$
