# Python pip: ".local/bin"
# Doom: ".config/emacs/bin"

# XDG
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache

# PATH
export PATH=$HOME/bin:$HOME/.local/bin:$HOME/go/bin:$PATH

export MANPAGER="sh -c 'col -bx | bat --language=man --style=plain --paging=always'"
export MANROFFOPT='-c'
export PAGER="less"
export LESS="-isMFXR"

export ALTERNATE_EDITOR=""
export EDITOR="nvim"
export VISUAL="nvim"

# TOOLS
export REDO_HISTORY_PATH=~/.zhistory
export BAT_THEME="Dracula"

# RIPGREP
export RIPGREP_CONFIG_PATH="${XDG_CONFIG_HOME}/ripgrep/config"

# FZF
export PATH=${PATH}:${HOME}/.fzf/bin
export FZF_DEFAULT_OPTS='--color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9 --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4'

# export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
export FZF_DEFAULT_COMMAND='fd --type file --hidden --no-ignore --exclude ".git"'

# Preview file content using bat (https://github.com/sharkdp/bat)
export FZF_CTRL_T_OPTS="
--preview 'bat -n --color=always {}'
--height=80%
--bind 'ctrl-/:change-preview-window(down|hidden|),ctrl-j:preview-down,ctrl-k:preview-up,ctrl-d:preview-page-down,ctrl-u:preview-page-up'"

# prevent pip clutter the global environment
export PIP_REQUIRE_VIRTUALENV=true

# RUST
export CARGO_HOME=$XDG_CONFIG_HOME/cargo
export RUSTUP_HOME=$XDG_CONFIG_HOME/rustup
export PATH=${PATH}:${XDG_CONFIG_HOME}/cargo/bin
export RUSTC_WRAPPER=sccache

# GEM
export GEM_HOME=${XDG_DATA_HOME}/gem
export PATH=${PATH}:${GEM_HOME}/bin

# STOW
export STOW_SRC_DIR=${HOME}/.local/stow
# only needed if not using the default
# export STOW_DEST_DIR=${HOME}/.local/

# Android SDK
export ANDROID_HOME=${HOME}/Android/Sdk
export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools

# Flutter SDK
export PATH=${PATH}:/opt/flutter/bin

#XDG-Ninja findings
# export CCACHE_DIR="${XDG_CACHE_HOME}"/ccache
# export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
# export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
# export VAGRANT_HOME="$XDG_DATA_HOME"/vagrant
# export WGETRC="$XDG_CONFIG_HOME/wgetrc"
# # issues while XForwarding
# # export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority
# export HISTFILE="$XDG_STATE_HOME"/zsh/history
