# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/.config/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# ZSH_TMUX_AUTOSTART="true"
ZSH_TMUX_CONFIG="${HOME}/.config/tmux/tmux.conf"

# Bundles from the default repo (robbyrussell's oh-my-zsh).
# antigen bundle command-not-found
antigen bundle fd
antigen bundle fzf
antigen bundle git
antigen bundle git-auto-fetch
antigen bundle git-extras
antigen bundle history
antigen bundle pip
antigen bundle python
antigen bundle ripgrep
antigen bundle sudo
antigen bundle tmux
antigen bundle sheeki03/ohmyzsh-tirith 
antigen bundle zoxide

# antigen bundle virtualenvwrapper
# antigen bundle "MichaelAquilina/zsh-autoswitch-virtualenv"

# Syntax highlighting bundle.
# antigen bundle zsh-users/zsh-syntax-highlighting

#antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions

# antigen theme dracula/zsh dracula
antigen theme romkatv/powerlevel10k

# Tell Antigen that you're done.
antigen apply

config_dir="${HOME}/.zsh"
for file in "${config_dir}"/*.zsh; do
  # Check if the file exists to avoid trying to source non-existent files
  # which can happen in bash if there are no .zsh files in the directory.
  if [[ -f "$file" ]]; then
    source "$file"
  fi
done

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)
