return {
  -- {
  --   "stevearc/conform.nvim",
  --   opts = {
  --     formatters_by_ft = {
  --       python = { "ruff_fix", "ruff_format" },
  --       shell = { "shfmt" },
  --     },
  --   },
  -- },
  -- {
  --   "mfussenegger/nvim-lint",
  --   opts = {
  --     -- Event to trigger linters
  --     events = { "BufWritePost", "BufReadPost" },
  --     linters_by_ft = {
  --       python = { "ruff", "mypy" },
  --       shell = { "shellcheck" },
  --       yaml = { "yamllint" },
  --     },
  --   },
  -- },
}
